name: Tester
on: [push, pull_request]

jobs:
  PHPUnit:
    name: php-${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.2
          - 7.3
    container:
      image: yansongda/php-fpm:${{ matrix.php }}
    steps:
      - name: Install Git
        run: apt update && apt install -y git
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
